stages:
  train:
    executor:
      module: scripts/train.py
      raw_help: "Traceback (most recent call last):\n  File \"/mnt/c/Users/james/CC\
        \ Allowed/vol_cfm/scripts/train.py\", line 13, in <module>\n    from cfm.cli\
        \ import setup_logging\nModuleNotFoundError: No module named 'cfm'\n"
      args: []
  generate:
    executor:
      module: scripts/generate.py
      raw_help: "Traceback (most recent call last):\n  File \"/mnt/c/Users/james/CC\
        \ Allowed/vol_cfm/scripts/generate.py\", line 14, in <module>\n    import\
        \ numpy as np\nModuleNotFoundError: No module named 'numpy'\n"
      args: []
  evaluate:
    executor:
      module: scripts/evaluate.py
      raw_help: "Traceback (most recent call last):\n  File \"/mnt/c/Users/james/CC\
        \ Allowed/vol_cfm/scripts/evaluate.py\", line 14, in <module>\n    import\
        \ numpy as np\nModuleNotFoundError: No module named 'numpy'\n"
      args: []
